/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package da_qlnhatro;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author PhanTuan
 */
public class frm_Index extends javax.swing.JFrame {

    /**
     * Creates new form frm_Index2
     */
    int status;
    public frm_Index() {
        initComponents();
        
        
        this.setLocationRelativeTo(null); 
        this.setResizable(false);
        this.setTitle("HỆ THỐNG QUẢN LÝ NHÀ TRỌ/TRANG CHỦ");
        // Lấy đường dẫn gốc
         String workingDir = System.getProperty("user.dir"); 
        // truyền vào đường dẫn gốc và đường dẫn đến img
         String file = workingDir + "/src/main/java/IMG/bgIMG.JPG"; 
         // Định dạng image
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(file).getImage().getScaledInstance(800, 550, Image.SCALE_SMOOTH));
        //Set IMG vào label
        bg.setIcon(imageIcon);
        // Kiểm tra quyền
        checkRole();

        
    }
    /**
     * Phương thức kiểm tra quyền
     */
    void checkRole()
    {
        if(lbl_role.getText().equals("Admin"))
        {
            btn_QLTK.setVisible(true);
            
            status = 1;
        }
        else
        {
            btn_QLTK.setVisible(false);
            status = 0;
        }
    }
    /**
     * Phương thức lấy tên user và gán vào label Name
     * @param username  - Tên User
     */
     public void setTenUser(String username)
    { 
        this.lbl_Username.setText(username);
    }
 
    /**
     * Phương thức lấy role và gán vào label role
     * @param Role 
     */
    public void setRoleName(String Role)
    { 
        this.lbl_role.setText(Role);
        // Kiểm tra lại role
        checkRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Username = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_QLBill = new javax.swing.JButton();
        btn_QLPhong = new javax.swing.JButton();
        btn_QLHD = new javax.swing.JButton();
        btn_QLKH = new javax.swing.JButton();
        btn_QLKV = new javax.swing.JButton();
        btn_QLDienNuoc = new javax.swing.JButton();
        btn_QLTK = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        HỆ THỐNG QUẢN LÝ NHÀ TRỌ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");

        lbl_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Username.setText("Name");

        lbl_role.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_role.setForeground(new java.awt.Color(255, 255, 255));
        lbl_role.setText("lbl_Role");

        btn_logout.setText("Đăng xuất");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_role)
                    .addComponent(lbl_Username))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_Username))
                .addGap(18, 18, 18)
                .addComponent(lbl_role)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_QLBill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLBill.setText("QUẢN LÝ HÓA ĐƠN");
        btn_QLBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLBillActionPerformed(evt);
            }
        });

        btn_QLPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLPhong.setText("QUẢN LÝ PHÒNG");
        btn_QLPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLPhongActionPerformed(evt);
            }
        });

        btn_QLHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLHD.setText("QUẢN LÝ HỢP ĐỒNG");
        btn_QLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHDActionPerformed(evt);
            }
        });

        btn_QLKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLKH.setText("QUẢN LÝ KHÁCH HÀNG");
        btn_QLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKHActionPerformed(evt);
            }
        });

        btn_QLKV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLKV.setText("QUẢN LÝ KHU VỰC");
        btn_QLKV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLKVActionPerformed(evt);
            }
        });

        btn_QLDienNuoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLDienNuoc.setText("QUẢN LÝ ĐIỆN NƯỚC");
        btn_QLDienNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLDienNuocActionPerformed(evt);
            }
        });

        btn_QLTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_QLTK.setText("QUẢN LÝ TÀI KHOẢN");
        btn_QLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_QLDienNuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_QLKV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_QLBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_QLKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btn_QLHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_QLPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_QLTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_QLBill, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QLKV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_QLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QLDienNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QLPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QLBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLBillActionPerformed
        frm_Bill B = new frm_Bill();
        B.setVisible(true);
        this.dispose();
        // Nếu 
        if(status == 1)
        {
            B.getRole(1);
          
        }
        else
        {
            B.getRole(0);
           
        }   
        B.getNames(lbl_Username.getText());
             
    }//GEN-LAST:event_btn_QLBillActionPerformed

    private void btn_QLPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLPhongActionPerformed
        frm_Room R = new frm_Room();
        R.setVisible(true);
            
        
    }//GEN-LAST:event_btn_QLPhongActionPerformed

    private void btn_QLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHDActionPerformed
        frm_Contract Contract = new frm_Contract();
        Contract.setVisible(true);
        this.dispose();
        // Truyền status qua form khác
        if(status == 1)
        {
            Contract.getRole(1);
          
        }
        else
        {
            Contract.getRole(0);
           
        }   
        Contract.getNames(lbl_Username.getText());
    }//GEN-LAST:event_btn_QLHDActionPerformed

    private void btn_QLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKHActionPerformed
        frm_Customer KH = new frm_Customer();
        KH.setVisible(true);
        
       
    }//GEN-LAST:event_btn_QLKHActionPerformed

    private void btn_QLKVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLKVActionPerformed
        frm_Area KV = new frm_Area();
        KV.setVisible(true);
        this.dispose();
         // Truyền status qua form khác
        if(status == 1)
        {
            KV.getRole(1);
          
        }
        else
        {
            KV.getRole(0);
           
        }   
        KV.getNames(lbl_Username.getText());
        
    }//GEN-LAST:event_btn_QLKVActionPerformed

    private void btn_QLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLTKActionPerformed
        frm_UserAccount User = new frm_UserAccount();
        User.setVisible(true);
        this.dispose();
         // Truyền status qua form khác
        if(status == 1)
        {
            User.getRole(1);
          
        }
        else
        {
            User.getRole(0);
           
        }   
        User.getNames(lbl_Username.getText());
    }//GEN-LAST:event_btn_QLTKActionPerformed

    private void btn_QLDienNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLDienNuocActionPerformed
        frm_DienNuoc DN = new frm_DienNuoc();
        DN.setVisible(true);
        this.dispose();
         // Truyền status qua form khác
        if(status == 1)
        {
            DN.getRole(1);
          
        }
        else
        {
            DN.getRole(0);
           
        }   
        DN.getNames(lbl_Username.getText());
    }//GEN-LAST:event_btn_QLDienNuocActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        frm_Login login = new frm_Login();
        login.setVisible(true);
        
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_QLBill;
    private javax.swing.JButton btn_QLDienNuoc;
    private javax.swing.JButton btn_QLHD;
    private javax.swing.JButton btn_QLKH;
    private javax.swing.JButton btn_QLKV;
    private javax.swing.JButton btn_QLPhong;
    private javax.swing.JButton btn_QLTK;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_role;
    // End of variables declaration//GEN-END:variables
}
